name: CI/CD

on:
    push:
        branches:
            - dev

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Build application
              run: bun run build

            - name: Vercel Action
              uses: amondnet/vercel-action@v19
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
